update_matches_status:
  cron: "*/30 * * * *"
  class: "UpdateMatchStatusWorker"
  queue: default
  args: ["https://www.cricbuzz.com/cricket-match/live-scores/recent-matches"]
  description: "update matches status in every 30 minutes"
scrape_teams:
  cron: "1 3 * * *"
  class: "TeamDataWorker"
  queue: default
  args: ["https://www.cricbuzz.com/cricket-team"]
  description: "update teams information every day at 3:01 am"
update_upcoming_matches:
  cron: "0 */3 * * *"
  class: "UpcomingMatchesWorker"
  queue: default
  args: [["https://www.cricbuzz.com/cricket-schedule/upcoming-series/international", "https://www.cricbuzz.com/cricket-schedule/upcoming-series/league"]]
  description: "update upcoming matches in every 3 hours"
update_team_squad_members:
  cron: "0 */6 * * *"
  class: "TeamSquadMemberWorker"
  queue: default
  description: "update team squad members of matches in every 6 hours"
update_live_scores:
  cron: "* * * * *"
  class: "LiveScoreWorker"
  queue: critical
  description: "update live-scores of live matches in every 2 minutes"
